# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeAshapeRcpp <- function(delvor_obj, alpha) {
    .Call(`_RcppAlphahull_computeAshapeRcpp`, delvor_obj, alpha)
}

computeVoronoiRcpp <- function(x, y) {
    .Call(`_RcppAlphahull_computeVoronoiRcpp`, x, y)
}

