# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeAhullRcpp <- function(ashape) {
    .Call(`_RcppAlphahull_computeAhullRcpp`, ashape)
}

computeAshapeRcpp <- function(delvor_obj, alpha) {
    .Call(`_RcppAlphahull_computeAshapeRcpp`, delvor_obj, alpha)
}

testRcpp <- function() {
    invisible(.Call(`_RcppAlphahull_testRcpp`))
}

computeVoronoiRcpp <- function(x, y) {
    .Call(`_RcppAlphahull_computeVoronoiRcpp`, x, y)
}

