# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.computeAhullRcpp <- function(ashape) {
    .Call('_RcppAlphahull_computeAhullRcpp', PACKAGE = 'RcppAlphahull', ashape)
}

.computeAshapeRcpp <- function(delvor_obj, alpha) {
    .Call('_RcppAlphahull_computeAshapeRcpp', PACKAGE = 'RcppAlphahull', delvor_obj, alpha)
}

.computeComplement <- function(mesh, alpha) {
    .Call('_RcppAlphahull_computeComplement', PACKAGE = 'RcppAlphahull', mesh, alpha)
}

.inahullRcpp <- function(complement, x, y) {
    .Call('_RcppAlphahull_inahullRcpp', PACKAGE = 'RcppAlphahull', complement, x, y)
}

testRcpp <- function() {
    invisible(.Call('_RcppAlphahull_testRcpp', PACKAGE = 'RcppAlphahull'))
}

.computeVoronoiRcpp <- function(x, y) {
    .Call('_RcppAlphahull_computeVoronoiRcpp', PACKAGE = 'RcppAlphahull', x, y)
}

